# Name of your workflow
name: Deploy React App to GitHub Pages

# Controls when the action will run.
# This workflow runs on pushes to the "main" branch.
on:
  push:
    branches:
      - main

# Add this permissions block to allow the action to push to your repository
permissions:
  contents: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build-and-deploy"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Step 1: Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2: Sets up Node.js so you can use npm commands
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      # Step 3: Installs the project dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Builds the app for production
      - name: Build
        run: npm run build

      # Step 5: Deploys the build folder to the 'gh-pages' branch
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist